### ISSUE TITLE
exit function error. ie user press ctrl C twice

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#2]
[0:00:00] initializing PixieWPS attack on DG1670000 (00000000:27:80)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] PIN found:     76796517

 [0:00:00] initializing PixieWPS attack on Wiley0000 (00000000:D7:40)

 [!] unable to complete in 75 seconds
 [+] skipping pixiewps on WileyRiley

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on DVW320000 (00000000:3E:6B)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on atlantis2010000 (00000000:6D:15)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on 407009EA0000 (00000000:20:20)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] PIN found:     35403876

 [0:00:00] initializing PixieWPS attack on DVW3200000 (00000000:A9:5E)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on DG1670000 (00000000:1E:90)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
^C
 (^C) Pixiewps attack interrupted

 [+] 17 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): e
Traceback (most recent call last):
  File "./wifitemod", line 3148, in <module>
    main()
  File "./wifitemod", line 324, in main
    need_handshake = not wps_attack(iface, t)
  File "./wifitemod", line 2930, in wps_attack
    send_interrupt(proc)
UnboundLocalError: local variable 'proc' referenced before assignment
root@*****:~/wifite-mod-pixiewps-master#

**Comment by aanarchyy** [comment]
Fixed
