### ISSUE TITLE
-mac parameter raise error

### ISSUE THREAD

**Issue by postak05** [aanarchyy/wifite-mod-pixiewps#32]
Running wifite with "-mac" parameter raise error:

 [+] scanning for wireless devices...
phy1
Traceback (most recent call last):
  File "/usr/bin/wifite-ng", line 3296, in <module>
    main()
  File "/usr/bin/wifite-ng", line 265, in main
    iface = get_iface()
  File "/usr/bin/wifite-ng", line 1041, in get_iface
    mac_anonymize(monitor)
  File "/usr/bin/wifite-ng", line 1653, in mac_anonymize
    ORIGINAL_IFACE_MAC = (iface, old_mac)
UnboundLocalError: local variable 'old_mac' referenced before assignment

**Comment by r3k2** [comment]
same error here..
