### ISSUE TITLE
crtl C, then option "e" to exit script

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#4]
[0:00:00] initializing PixieWPS attack on LUZ DESIG000000 (000000:C8:30)

 [!] unable to complete in 70 seconds
 [+] skipping pixiewps on LUZ DESI000000

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on NETGEAR17 (0000000:1C:A5)
 [+] E-Nonce found
 [+] PKE hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on FULTO000000 (0000000:28:50)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on SprintGa000000 (0000000:82:F6)
^C
 (^C) Pixiewps attack interrupted

 [+] 2 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): e
Traceback (most recent call last):
  File "./wifitemod", line 3164, in <module>
    main()
  File "./wifitemod", line 325, in main
    need_handshake = not wps_attack(iface, t)
  File "./wifitemod", line 2939, in wps_attack
    send_interrupt(proc)
UnboundLocalError: local variable 'proc' referenced before assignment

**Comment by aanarchyy** [comment]
Fixed, Thanks.
