### ISSUE TITLE
crtl C, during pixie attack, then option "e"

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#5]
[0:00:00] initializing PixieWPS attack on FULTON EXP000000000 (00000000:28:50)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] PIN found:     36799084
 [+] Handing pin to reaver

 [0:00:00] initializing WPS PIN attack on FULTON EXP000000000 (00000000:28:50)
 [0:00:14] WPS attack, 0/2 success/ttl, 

 [+] PIN found:     36799084
 [+] WPA key found: 0000000000

 [0:00:00] initializing PixieWPS attack on ai00000 (0000000:24:65)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on NETG00000(0000000:1C:A5)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on TP-LINK_300000 (0000000:68:60)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on METR000000 (00000000:1B:C1)
^C
 (^C) Pixiewps attack interrupted

 [+] 5 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): c

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on LUZ DES000000000 (00000000:C8:30)
 [+] E-Nonce found
 [+] PKE hash found
^C
 (^C) Pixiewps attack interrupted

 [+] 4 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): e
Traceback (most recent call last):
  File "./wifitemod", line 3164, in <module>
    main()
  File "./wifitemod", line 325, in main
    need_handshake = not wps_attack(iface, t)
  File "./wifitemod", line 2939, in wps_attack
    send_interrupt(proc)
UnboundLocalError: local variable 'proc' referenced before assignment

**Comment by aanarchyy** [comment]
Duplicate.

**Comment by nuroo** [comment]
Oh Sorry. I thought if script errored at a different line, different error
