### ISSUE TITLE
error during wpa capture after pixie attack

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#8]
[0:00:00] initializing PixieWPS attack on DVW320000 (000000:3E:6B)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!
False
 [0:08:20] starting wpa handshake capture on "DVW320000"
 [0:08:13] listening for handshake...  
 (^C) WPA handshake capture interrupted

 [+] 47 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): c

 [0:00:00] initializing PixieWPS attack on b0c55400000 (000000:A7:86)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!
False
 [0:08:20] starting wpa handshake capture on "b0c554000000"
 [0:07:35] listening for handshake...  
 (^C) WPA handshake capture interrupted

 [+] 46 targets remain
 [+] what do you want to do?
     [c]ontinue attacking targets
     [e]xit completely
 [+] please make a selection (c, or e): c

 [0:00:00] initializing PixieWPS attack on Tupp0000 (0000000:07:00)

 [!] unable to complete in 70 seconds
 [+] skipping pixiewps on Tuppy Glossop

 [+] Pixiewps attack failed!
False
 [0:08:20] starting wpa handshake capture on "Tuppy Glo00000"
Traceback (most recent call last):...  
  File "./wifitemod", line 3164, in <module>
    main()
  File "./wifitemod", line 333, in main
    if wpa_get_handshake(iface, t, ts_clients):
  File "./wifitemod", line 1931, in wpa_get_handshake
    if has_handshake(target, temp + 'wpa-01.cap.temp'):
  File "./wifitemod", line 2152, in has_handshake
    valid_handshake = has_handshake_tshark(target, capfile)
  File "./wifitemod", line 2054, in has_handshake_tshark
    msg = fields[9][0]      # The message number (1, 2, 3, or 4)
IndexError: list index out of range

**Comment by aanarchyy** [comment]
Not sure what's going on with that, that's part of the origional code that I didn't write.  I'll see if I can figure it out though.

**Comment by nuroo** [comment]
Would you prefer I only trouble shoot new additions only?

**Comment by aanarchyy** [comment]
No, keep doing what your'e doing, I appreciate it.  I would like if everything  worked anyway, and this one is hopefully fixed also.

**Comment by aanarchyy** [comment]
I can't seem to reproduce this so I'm not sure what is happening.

**Comment by nuroo** [comment]
I will try to gather more info on this

**Comment by SubZero5** [comment]
I am not 100% sure but this was one of the reasons of wifite got handled by @brainpow. Please examine his changelog.md and wifite.py
